declare const styles: {
  readonly "main": string;
  readonly "section": string;
  readonly "inner": string;
  readonly "innerContents": string;
  readonly "middleContents": string;
  readonly "future": string;
  readonly "time": string;
  readonly "ranking": string;
  readonly "mode": string;
  readonly "share": string;
  readonly "floatContents": string;
  readonly "sharePeace": string;
  readonly "modePeace": string;
  readonly "rankingPeace": string;
  readonly "timePeace": string;
  readonly "piece1": string;
  readonly "piece2": string;
  readonly "piece3": string;
  readonly "piece4": string;
  readonly "landingLogin": string;
  readonly "picturesSection": string;
  readonly "picturesSectionContainer": string;
  readonly "picturesSectionIcons": string;
  readonly "picturesSectionIconsItem": string;
  readonly "square": string;
  readonly "circleBackground": string;
  readonly "circleBackgroundBlue": string;
  readonly "circleBackgroundPeople": string;
  readonly "circleBackgroundOrange": string;
  readonly "open": string;
  readonly "picturesSectionUnderBody": string;
  readonly "picturesSectionUnderBodyContainer": string;
};
export = styles;

